"""DOCX renderer — python-docx."""

from __future__ import annotations

import re
from pathlib import Path

from iesolver.state import SolverState


def _strip_md(text: str) -> str:
    """Remove markdown markers; keep readable plain text."""
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    text = re.sub(r"```[\s\S]*?```", lambda m: m.group(0).replace("```", ""), text)
    return text.strip()


def _add_section(doc: object, heading: str, content: str) -> None:
    from docx.shared import Pt  # type: ignore[import]

    doc.add_heading(heading, level=1)  # type: ignore[attr-defined]
    for para in _strip_md(content).split("\n\n"):
        para = para.strip()
        if not para:
            continue
        p = doc.add_paragraph(para)  # type: ignore[attr-defined]
        p.style.font.size = Pt(10)


def write_docx(state: SolverState, output_path: Path) -> Path:
    """Render *state* to a .docx file at *output_path*."""
    from datetime import datetime

    from docx import Document  # type: ignore[import]
    from docx.shared import Inches, Pt  # type: ignore[import]
    from docx.enum.text import WD_ALIGN_PARAGRAPH  # type: ignore[import]

    doc = Document()

    # ---- Title page ----
    title = doc.add_heading("Industrial Engineering Problem Report", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    goal = doc.add_paragraph()
    goal.add_run("Problem Statement:  ").bold = True
    goal.add_run(state.get("explicit_goal", "") or "")

    meta = doc.add_paragraph()
    meta.add_run(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}").italic = True

    exec_res = state.get("execution_result", "") or ""
    if exec_res:
        res_p = doc.add_paragraph()
        res_p.add_run("Optimal Result:  ").bold = True
        res_p.add_run(exec_res)

    is_valid = state.get("is_valid")
    if is_valid is not None:
        val_p = doc.add_paragraph()
        val_p.add_run("Validation Status:  ").bold = True
        val_p.add_run("✓ Validated" if is_valid else "✗ Not Validated")

    doc.add_page_break()

    # ---- Content sections ----
    _add_section(doc, "Executive Summary", state.get("executive_summary", "") or "")
    _add_section(doc, "Technical Analysis", state.get("technical_output", "") or "")

    if state.get("sensitivity_results"):
        _add_section(doc, "Sensitivity Analysis", state.get("sensitivity_results", "") or "")

    _add_section(doc, "Action Directives", state.get("action_directives", "") or "")

    # ---- Figures ----
    figures = state.get("figures") or []
    if figures:
        doc.add_heading("Charts", level=1)
        for fig_path in figures:
            p = Path(fig_path)
            if p.exists():
                doc.add_picture(str(p), width=Inches(5.5))

    # ---- Metrics table ----
    metrics: dict = state.get("metrics") or {}
    if metrics:
        doc.add_heading("Performance Metrics", level=1)
        cols = ["Node", "LLM Calls", "Tokens In", "Tokens Out", "Cost (USD)", "Latency (ms)"]
        table = doc.add_table(rows=1 + len(metrics), cols=len(cols))
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        for i, c in enumerate(cols):
            hdr[i].text = c
            hdr[i].paragraphs[0].runs[0].bold = True
        for row_idx, (node, m) in enumerate(metrics.items(), start=1):
            cells = table.rows[row_idx].cells
            cells[0].text = node
            cells[1].text = str(m.get("llm_calls", 0))
            cells[2].text = str(m.get("tokens_in", 0))
            cells[3].text = str(m.get("tokens_out", 0))
            cells[4].text = f"${m.get('cost_usd', 0) or 0:.4f}"
            cells[5].text = f"{m.get('latency_ms', 0) or 0:.0f}"

    doc.add_paragraph(
        "\n\nGenerated by iesolver · Powered by DSPy + LangGraph"
    ).italic = True

    doc.save(str(output_path))
    return output_path
