"""PDF renderer — fpdf2 (pure-Python, no system dependencies)."""

from __future__ import annotations

import re
import textwrap
from pathlib import Path

from iesolver.state import SolverState

# Page geometry
_LM = 20   # left margin mm
_RM = 20   # right margin mm
_TM = 20   # top margin mm
_BM = 20   # bottom margin mm


def _strip_md(text: str) -> str:
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    text = re.sub(r"```[\s\S]*?```", lambda m: m.group(0).replace("```", ""), text)
    return text.strip()


def _safe(text: str) -> str:
    """Drop characters outside latin-1 range so core fonts don't crash."""
    return text.encode("latin-1", "replace").decode("latin-1")


class _IEReportPDF:
    """Thin wrapper around FPDF for 3-section IE reports."""

    def __init__(self) -> None:
        from fpdf import FPDF  # type: ignore[import]

        self._pdf = FPDF(orientation="P", unit="mm", format="A4")
        self._pdf.set_margins(_LM, _TM, _RM)
        self._pdf.set_auto_page_break(auto=True, margin=_BM)
        self._pdf.add_page()

    # ------------------------------------------------------------------
    def title_block(self, goal: str, result: str, is_valid: bool | None, ts: str) -> None:
        p = self._pdf
        p.set_font("Helvetica", "B", 16)
        p.set_fill_color(29, 78, 216)
        p.set_text_color(255, 255, 255)
        p.cell(0, 12, _safe("Industrial Engineering Problem Report"), fill=True,
               align="C", new_x="LMARGIN", new_y="NEXT")

        p.set_font("Helvetica", "", 9)
        p.set_fill_color(239, 246, 255)
        p.set_text_color(30, 41, 59)
        p.multi_cell(0, 6, _safe(f"Problem: {goal}"), fill=True)
        p.ln(1)

        p.set_font("Helvetica", "I", 8)
        p.set_text_color(100, 116, 139)
        status = ""
        if is_valid is not None:
            status = "  |  Validated: YES" if is_valid else "  |  Validated: NO"
        p.cell(0, 6, _safe(f"Generated: {ts}{status}"), new_x="LMARGIN", new_y="NEXT")

        if result:
            p.ln(2)
            p.set_font("Helvetica", "B", 9)
            p.set_text_color(22, 101, 52)
            p.cell(0, 6, _safe(f"Result: {result}"), new_x="LMARGIN", new_y="NEXT")

        p.ln(4)
        p.set_text_color(30, 41, 59)

    def section(self, title: str, content: str) -> None:
        p = self._pdf
        p.set_font("Helvetica", "B", 11)
        p.set_fill_color(241, 245, 249)
        p.set_draw_color(29, 78, 216)
        p.cell(0, 8, _safe(title), fill=True, border="L", new_x="LMARGIN", new_y="NEXT")
        p.ln(2)

        if not content:
            return

        p.set_font("Helvetica", "", 9)
        plain = _strip_md(content)
        for line in plain.splitlines():
            stripped = line.rstrip()
            if not stripped:
                p.ln(3)
                continue
            # Wrap long lines to fit page width
            for chunk in textwrap.wrap(stripped, width=100) or [stripped]:
                p.multi_cell(0, 5, _safe(chunk), new_x="LMARGIN", new_y="NEXT")
        p.ln(4)

    def metrics_table(self, metrics: dict) -> None:
        if not metrics:
            return
        p = self._pdf
        self.section("Performance Metrics", "")
        cols   = ["Node", "Calls", "Tok In", "Tok Out", "Cost", "ms"]
        widths = [45, 18, 18, 18, 22, 18]
        p.set_font("Helvetica", "B", 8)
        p.set_fill_color(241, 245, 249)
        for col, w in zip(cols, widths):
            p.cell(w, 6, col, border=1, fill=True)
        p.ln()
        p.set_font("Helvetica", "", 8)
        for node, m in metrics.items():
            row = [
                node,
                str(m.get("llm_calls", 0)),
                str(m.get("tokens_in", 0)),
                str(m.get("tokens_out", 0)),
                f"${m.get('cost_usd', 0) or 0:.4f}",
                f"{m.get('latency_ms', 0) or 0:.0f}",
            ]
            for val, w in zip(row, widths):
                p.cell(w, 5, _safe(val), border=1)
            p.ln()
        p.ln(4)

    def footer_text(self) -> None:
        p = self._pdf
        p.set_y(-15)
        p.set_font("Helvetica", "I", 7)
        p.set_text_color(150, 150, 150)
        p.cell(0, 5, "Generated by iesolver  ·  Powered by DSPy + LangGraph", align="C")

    def save(self, path: Path) -> None:
        self.footer_text()
        self._pdf.output(str(path))


def write_pdf(state: SolverState, output_path: Path) -> Path:
    """Render *state* to a PDF file at *output_path* using fpdf2."""
    from datetime import datetime

    doc = _IEReportPDF()
    doc.title_block(
        goal=state.get("explicit_goal", "IE Problem") or "IE Problem",
        result=state.get("execution_result", "") or "",
        is_valid=state.get("is_valid"),
        ts=datetime.now().strftime("%Y-%m-%d %H:%M"),
    )

    doc.section("Executive Summary",   state.get("executive_summary", "")  or "")
    doc.section("Technical Analysis",  state.get("technical_output", "")   or "")
    if state.get("sensitivity_results"):
        doc.section("Sensitivity Analysis", state.get("sensitivity_results", "") or "")
    doc.section("Action Directives",   state.get("action_directives", "")  or "")
    doc.metrics_table(state.get("metrics") or {})

    doc.save(output_path)
    return output_path
